---

- name: Install mysql
  package: name={{item}} state=present
  with_items:
  - mysql-server
  - php5
  - libapache2-mod-php5

- name: Configure
  shell: mysql_secure_installation

- name: To start mysql
  service:
   name: mysql
   state: started
   enabled: yes
